services:
  diagnostics:
    platform: linux/arm64 # Run in arm64 linux container
    image: ratatoskr/diagnostics # Namespaced artifact (image) name

    build:
      context: .
      dockerfile: ./src-diagnostics/Dockerfile

  broker:
    platform: linux/arm64
    image: ratatoskr/broker

    build:
      context: .
      dockerfile: ./src-broker/Dockerfile

    ports:
      - "1883:1883"
