services:
  broker:
    platform: linux/arm64 # Run in arm64 linux container
    image: ratatoskr/broker # Namespaced artifact (image) name

    build:
      context: .
      dockerfile: ./src-broker/Dockerfile

    ports:
      - "1883:1883"

  diagnostics:
    platform: linux/arm64
    image: ratatoskr/diagnostics

    build:
      context: .
      dockerfile: ./src-diagnostics/Dockerfile

    depends_on:
      - broker
