services:
  diagnostics:
    platform: linux/arm64 # Run in arm64 linux container

    build:
      context: .
      dockerfile: ./src-diagnostics/Dockerfile

  broker:
    platform: linux/arm64

    build:
      context: .
      dockerfile: ./src-broker/Dockerfile

    ports:
      - "1883:1883"
