name: CI Workflow for automated testing of the weatherflow project

on:
    push:
        branches: 
            - main
            - development
    pull_request:
        branches:
            - main
            - development

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            DOCKER_BUILDKIT: 1

        steps:
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            with:
              platforms: linux/arm64

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Configure QEMU
            run: |
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

          - name: Checkout repo
            uses: actions/checkout@v2

          - name: Build docker image
            run: |
              docker build --platform linux/arm64 -t sensorstorm-host-image .

          - name: Save docker image
            run: |
              docker save sensorstorm-host-image > sensorstorm-host-image.tar

          - name: Upload build image as artifact
            uses: actions/upload-artifact@v4
            with:
              name: sensorstorm-host-image
              path: "./sensorstorm-host-image.tar"
              if-no-files-found: error
              compression-level: 6
              overwrite: true

    weather-station:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                platforms: linux/arm64

            - name: Configure QEMU
              run: |
                docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

            - name: Download the compiled artifact / application setup
              uses: actions/download-artifact@v4
              with:
                name: sensorstorm-host-image

            - name: Load the docker image
              run: |
                docker load -i sensorstorm-host-image.tar

            - name: Run unit tests for WeatherStation
              run: |
                docker run --rm --platform linux/arm64 sensorstorm-host-image ./build/bin/ws_unit_tests
